spring:
  application:
    name: mcp_server
  ai:
    mcp:
      server:
        name: mcp_server
        version: 1.0.0
        type: SYNC
        instructions: "Spring Boot MCP server providing mathematical operations and weather information tools"
        sse-endpoint: /sse
        sse-message-endpoint: /mcp/messages
        capabilities:
          tool: true
          resource: true
          prompt: true
          completion: true